### ISSUE TITLE
I too, would like to help.

### ISSUE THREAD

**Issue by ccioanca** [jscherer92/Quark#11]
Hey, I hope it's ok that I'm posting this as an issue.

There's nothing I hate more than electron apps, and so, there's nothing I'd love to see become a reality more than this.

I'm a full-stack/C# dev with effectively zero desktop experience in the grand scheme of things, but I'd like to help as much as I can anyways. I do have a background in digital design as well, so if there are any assets that you may need, such as logos and the like, I'd like to offer my skills in that department. 

Also feel free to put me down as an alpha/beta tester for when that comes around. I have a few web apps that I'd like to turn into desktop apps, but I can't bring myself to use Electron.

**Comment by jscherer92** [comment]
Thanks ccioanca! I'm currently working through the MVP base for windows right now. I'm currently sick so work has slowed down a bit, but I am working through rebuilding Node's Buffer object which will then lead into streaming.

I think once we see that this is a reality (it is for me especially once I wrapped my head around all the intricacies of getting into the browser object and injecting code in) we will be in a good position to start branding this project.

I mainly don't want to be premature on this project and make it the holy grail out there until we see the obvious benefit.

**Comment by ccioanca** [comment]
Too late man. The hype train has left the station.

**Comment by morajabi** [comment]
I agree it's our hope now! (Especially that you started working on Windows as it must be harder :D)
