### ISSUE TITLE
Perhaps we could use QT Web C++

### ISSUE THREAD

**Issue by jcampbell05** [jscherer92/Quark#16]
http://doc.qt.io/qt-5/topics-web-content.html

**Comment by jscherer92** [comment]
Interesting. Took a look at it as an overview and I would be interested on the distribution size. I'm still going to move forward with the current implementation, but it would be good to do a comparison once the Windows MVP is done.

**Comment by jscherer92** [comment]
I think going for a bare bones system is what we need to do to make this useful. While I thoroughly enjoy Qt, it is still quite a wrapper compared to just using the Win API or utilizing the base level system of an OS
