### ISSUE TITLE
Consider the use of low.js

### ISSUE THREAD

**Issue by paulocoghi** [jscherer92/Quark#21]
Maybe http://www.lowjs.org/ ( https://github.com/neonious/lowjs ) could be used in the core. I would like to know what you think :)

**Comment by jscherer92** [comment]
That looks really nice! I wish more work went into the Windows side of
things. I know how difficult it is but that is what makes it so difficult.

Even tried using Nim for cross OS support and it was not working well.

**Comment by jscherer92** [comment]
Closing out as its support is mainly for microcontrollers, not for Windows or Unix OS
