### ISSUE TITLE
MVP Design volunteers

### ISSUE THREAD

**Issue by jscherer92** [jscherer92/Quark#7]
Please post here if you are willing to volunteer for the design of the MVP! Thanks!

**Comment by norman784** [comment]
For design are you talking about the API design?

**Comment by jscherer92** [comment]
Two pieces and really I'm open to either of them.

1) how the shared library will look between systems.

2) What pieces of Electron and the Node API people can deem as needed for a MVP. An example would be that we may not need the http/https module since we can use the browsers fetch/XMLHTTPRequest system.

**Comment by styfle** [comment]
One day, fetch might even work in node core: https://github.com/nodejs/node/issues/19393

I think ‘fs’ is one of the most important core features from Node. 
And probably WebView and window open/close position is important from Electron.

**Comment by jscherer92** [comment]
@styfle those were a couple of the features that I was thinking

**Comment by norman784** [comment]
I agree with @styfle with those features we can launch the MVP.

About how the shared library will looks like I'm clueless, maybe when we have a functional windows library we can start looking on how the library is working and then start to build their public methods.

**Comment by jscherer92** [comment]
Awesome! I was messing around with the engine last night and got eventing working with the back end system. Windows is definitely a beast in terms of how to do things. I'm currently working on optimizing what I have and how to go about it.

**Comment by norman784** [comment]
IMO we don't need optimize it yet, we need to just get working everything and then we start to optimize it, because this is a prototype.

**Comment by jscherer92** [comment]
Yep yep! For me it is just making sure I'm deleting things when I should be. I guess I should say this is cleanup right now so it's not eating 40MB of RAM when it should only take 4
